#ifndef HEADERS_H
#define HEADERS_H

#include <algorithm>
#include <arpa/inet.h>
#include <assert.h>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <cstring>
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <functional>
#include <list>
#include <memory>
#include <mutex>
#include <netinet/in.h>
#include <queue>
#include <semaphore.h>
#include <signal.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <sys/epoll.h>
#include <sys/mman.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/uio.h>
#include <thread>
#include <time.h>
#include <typeindex>
#include <typeinfo>
#include <unistd.h>
#include <unordered_map>
#include <vector>

#endif